name: Deploy

# TODO: change
# on:
#   # only on tags which follow semantic versioning
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # TODO: change project path and service
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USER}}
          key: ${{secrets.SSH_PRIVATE_KEY}}
          port: ${{secrets.SSH_PORT}}
          script: |
            cd ~/GitHub/temp/srfvirus-spotify
            git fetch --all
            git pull
            sudo systemctl restart temp-srfvirus-spotify.service
