name: Deploy
env:
  SSH_HOST: ${{secrets.SSH_HOST}}
  SSH_PORT: ${{secrets.SSH_PORT}}
  SSH_USER: ${{secrets.SSH_USER}}
  SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}

# TODO: change
# on:
#   # only on tags which follow semantic versioning
#   push:
#     tags:
#       - "v[0-9]+.[0-9]+.[0-9]+"
on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # TODO: change project path and service
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: $SSH_HOST
          username: $SSH_USER
          key: $SSH_PRIVATE_KEY
          port: $SSH_PORT
          script: |
            cd ~/GitHub/temp/srfvirus-spotify
            git fetch --all
            git pull origin main 
            sudo systemctl restart temp-srfvirus-spotify.service
